// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cipher.proto

#include "cipher.pb.h"
#include "cipher.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace aircipher {

static const char* AirService_method_names[] = {
  "/aircipher.AirService/SendMessage",
};

std::unique_ptr< AirService::Stub> AirService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AirService::Stub> stub(new AirService::Stub(channel, options));
  return stub;
}

AirService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(AirService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AirService::Stub::SendMessage(::grpc::ClientContext* context, const ::aircipher::Message& request, ::aircipher::MessageAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::aircipher::Message, ::aircipher::MessageAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void AirService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::aircipher::Message* request, ::aircipher::MessageAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::aircipher::Message, ::aircipher::MessageAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void AirService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::aircipher::Message* request, ::aircipher::MessageAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::aircipher::MessageAck>* AirService::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::aircipher::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::aircipher::MessageAck, ::aircipher::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::aircipher::MessageAck>* AirService::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::aircipher::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

AirService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AirService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AirService::Service, ::aircipher::Message, ::aircipher::MessageAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AirService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::aircipher::Message* req,
             ::aircipher::MessageAck* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
}

AirService::Service::~Service() {
}

::grpc::Status AirService::Service::SendMessage(::grpc::ServerContext* context, const ::aircipher::Message* request, ::aircipher::MessageAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace aircipher

